apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  # Tránh bị xóa bởi argocd sync với Resources Hooks
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Default project (catch-all, full permissions)
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
