server.port=8080
spring.datasource.url=jdbc:postgresql://postgres-inventory:5432/inventory-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=ptechie
spring.datasource.password=password
eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka/

spring.kafka.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.minejava.inventoryservice.event.PaymentEvent
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc.datasource.init=DEBUG
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
