INSERT INTO inventory (sku_code, quantity)
SELECT 'IPHONE-15-PRO-256-TITANIUM', 12
WHERE NOT EXISTS (SELECT 1 FROM inventory WHERE sku_code = 'IPHONE-15-PRO-256-TITANIUM');

INSERT INTO inventory (sku_code, quantity)
SELECT 'SAMSUNG-S24-ULTRA-256-BLACK', 10
WHERE NOT EXISTS (SELECT 1 FROM inventory WHERE sku_code = 'SAMSUNG-S24-ULTRA-256-BLACK');

INSERT INTO inventory (sku_code, quantity)
SELECT 'MACBOOK-AIR-M3-13-512-MIDNIGHT', 8
WHERE NOT EXISTS (SELECT 1 FROM inventory WHERE sku_code = 'MACBOOK-AIR-M3-13-512-MIDNIGHT');

INSERT INTO inventory (sku_code, quantity)
SELECT 'AIRPODS-PRO-2-USB-C', 25
WHERE NOT EXISTS (SELECT 1 FROM inventory WHERE sku_code = 'AIRPODS-PRO-2-USB-C');

INSERT INTO inventory (sku_code, quantity)
SELECT 'IPAD-AIR-M2-11-128-WIFI', 14
WHERE NOT EXISTS (SELECT 1 FROM inventory WHERE sku_code = 'IPAD-AIR-M2-11-128-WIFI');

INSERT INTO inventory (sku_code, quantity)
SELECT 'SONY-WH1000XM5-BLACK', 18
WHERE NOT EXISTS (SELECT 1 FROM inventory WHERE sku_code = 'SONY-WH1000XM5-BLACK');
